### ISSUE TITLE
Type of Factory<T>.create is incorrect

### ISSUE THREAD

**Issue by TomMarius** [types/npm-generic-pool#9] opened 2016-10-24 10:00 UTC
**Now:**
`create: (callback: (err: Error | void, client?: T) => void) => void`

**Why is it an error:**
Correct usage: `create: (callback) => { MongoClient.connect("").then(connection => callback(null, connection)) },` now emits a type error: `Argument of type 'null' is not assignable to parameter of type 'void | Error'.`

**Correct type/fix:**
`create: (callback: (err: Error | null, client?: T) => void) => void`

**Comment by blakeembrey** [comment] 2016-11-11 19:41
You can use `undefined` as a workaround. This repo was typed for TS 1.x which meant having to resort to `void` before the `null` and `undefined` types were introduced.

**Comment by felixfbecker** [comment] 2016-11-11 19:42
This is a duplicate of https://github.com/goenning/typed-generic-pool/issues/6 and has been fixed: https://github.com/goenning/typed-generic-pool/issues/6. Imo now that TS2 is out we can switch to `Error | null` though.

**Comment by blakeembrey** [comment] 2016-11-11 19:44
@felixfbecker Sounds good. It should ideally be `Error | null | undefined`.

**Closed** 2016-11-13 01:58 UTC
